name: Daily Commit

on:
  schedule:
    - cron: "0 18 * * *"  # Roz 11:30 PM IST ke around chalega
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Updated on $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "your-username"
          git add .
          git commit -m "Daily auto commit"
          git push

